import tap_shopify.streams.abandoned_checkouts
import tap_shopify.streams.customers
import tap_shopify.streams.orders
import tap_shopify.streams.order_refunds
import tap_shopify.streams.metafields
import tap_shopify.streams.transactions
import tap_shopify.streams.products
import tap_shopify.streams.collects
import tap_shopify.streams.custom_collections
