import tap_shopify.streams.abandoned_checkouts
import tap_shopify.streams.customers
import tap_shopify.streams.orders
import tap_shopify.streams.order_refunds
import tap_shopify.streams.metafields
import tap_shopify.streams.transactions
import tap_shopify.streams.products
import tap_shopify.streams.collects
import tap_shopify.streams.custom_collections
import tap_shopify.streams.locations
import tap_shopify.streams.inventory_levels
import tap_shopify.streams.inventory_items
import tap_shopify.streams.shop
import tap_shopify.streams.price_rules
import tap_shopify.streams.discount_codes
import tap_shopify.streams.incoming_items
